# This is a basic workflow to help you get started with Actions

name: Production

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [production]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "deploy"
  deploy:
    name: ğŸš€ Deploy
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: ğŸ”‘ Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
          #name: id_rsa # optional
          #config: ${{ secrets.CONFIG }} # ssh_config; optional
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: ğŸšš Branch checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: production
      - name: ğŸ†” Configure repository to Umbler
        run: |
          git remote add umbler ${{ secrets.UMBLER_REMOTE }}
          git config --global user.email "contact@augustoicaro.com"
          git config --global user.name "Augusto Icaro Farias da Cunha"
          git cherry-pick 24368d5fd93e209006e5f451aacf2e3bae5589df
      - name: ğŸ”‘ Parser Firebase API key
        uses: jwsi/secret-parser@v1
        with:
          filename: package.json
          secret-name: FIREBASE_APIKEY
          secret-value: ${{ secrets.FIREBASE_APIKEY }}
      - name: ğŸ”‘ Parser Firebase M Sender Id
        uses: jwsi/secret-parser@v1
        with:
          filename: package.json
          secret-name: FIREBASE_MSENDERID
          secret-value: ${{ secrets.FIREBASE_MSENDERID }}
      - name: ğŸ”‘ Parser Firebase App Id
        uses: jwsi/secret-parser@v1
        with:
          filename: package.json
          secret-name: FIREBASE_APPID
          secret-value: ${{ secrets.FIREBASE_APPID }}
      - name: ğŸ”‘ Parser Firebase M Id
        uses: jwsi/secret-parser@v1
        with:
          filename: package.json
          secret-name: FIREBASE_MID
          secret-value: ${{ secrets.FIREBASE_MID }}
      - name: ğŸ”‘ Parser MSAL Client Id
        uses: jwsi/secret-parser@v1
        with:
          filename: package.json
          secret-name: MSAL_CLIENT_ID
          secret-value: ${{ secrets.MSAL_CLIENT_ID }}
      - name: ğŸ”‘ Parser MSAL Rdirect URI
        uses: jwsi/secret-parser@v1
        with:
          filename: package.json
          secret-name: MSAL_REDIRECT_URI
          secret-value: ${{ secrets.MSAL_REDIRECT_URI }}
      - name: ğŸ”‘ Parser MSAL Onedrive URI
        uses: jwsi/secret-parser@v1
        with:
          filename: package.json
          secret-name: ONEDRIVE_URI
          secret-value: ${{ secrets.ONEDRIVE_URI }}
      - name: ğŸ”‘ Parser Onedrive Nortan Folder ID
        uses: jwsi/secret-parser@v1
        with:
          filename: package.json
          secret-name: ONEDRIVE_NORTAN_ID
          secret-value: ${{ secrets.ONEDRIVE_NORTAN_ID }}
      - name: ğŸ”‘ Parser Onedrive Admin Folder ID
        uses: jwsi/secret-parser@v1
        with:
          filename: package.json
          secret-name: ONEDRIVE_ADM_ID
          secret-value: ${{ secrets.ONEDRIVE_ADM_ID }}
      - name: ğŸ”‘ Parser Nortan API Token
        uses: jwsi/secret-parser@v1
        with:
          filename: package.json
          secret-name: API_TOKEN
          secret-value: ${{ secrets.API_TOKEN }}
      - name: â¬†ï¸ Commit to Umbler using git remote
        run: |
          git add -A
          git commit -m"Replace Secrets"
          git push umbler production:master -f
